title = "ConfigFile"

local = "tijuca"
max_page = 50
postition_loc = 0
max_amenities = 10

tipo_contrato = "RENTAL"
tipo_propriedade = "USED"

urls_metro_trem = [
    "https://pt.wikipedia.org/wiki/Metr%C3%B4_do_Rio_de_Janeiro",
    "https://pt.wikipedia.org/wiki/SuperVia",
]

[site]
    [site.vivareal]
        site = "https://www.vivareal.com.br"
        api = "glue-api.vivareal.com"
        portal = "VIVAREAL"

    [site.zapimoveis]
        site = "https://www.zapimoveis.com.br"
        api = "glue-api.zapimoveis.com.br"
        portal = "ZAP"
