version: "3.9"
services:
    app:
        build: .
        environment:
            - PORT=5000
        ports:
            - "5000:5000"
        volumes:
            - "./data:/app/data"
            - "./logs:/app/logs"

volumes:
    data: 
        external: true