version: "3"
services:
  app:
    build:
      context: .
      dockerfile: app.dockerfile

  # shiny:
  #   build:
  #     context: .
  #     dockerfile: dash.dockerfile
  #   ports:
  #     - "3838:3838"
