version: "3.9"
services:
    app:
        build: .
        restart: always
        env_file: 
            - ./.env
        ports:
            - ${PORT}:${PORT}
        networks:
            - network
        depends_on:
            - db

    db:
        image: postgres
        restart: always
        env_file: 
            - ./.env
        ports:
            - "15432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - network

networks: 
    network:

volumes:
    pgdata:

