[tool.poetry]
name = "get_imoveis"
version = "0.1.0"
description = ""
authors = ["Douglas Braga <douglasmartinsbraga@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
selenium = "^3.141.0"
pandas = "^1.2.3"
jsonlines = "^2.0.0"
Scrapy = "^2.4.1"
geopy = "^2.1.0"
pyarrow = "^3.0.0"
scikit-learn = "^0.24.1"
lightgbm = "^3.1.1"
scikit-optimize = "^0.8.1"
xgboost = "^1.3.3"
Flask = "^1.1.2"
Flask-Bootstrap = "^3.3.7"
folium = "^0.12.1"
toml = "^0.10.2"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
jupyterlab = "^3.0.10"
matplotlib = "^3.3.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
