[tool.poetry]
name = "get_imoveis"
version = "0.1.0"
description = ""
authors = ["Douglas Braga <douglasmartinsbraga@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
selenium = "^3.141.0"
pandas = "^1.2.3"
jsonlines = "^2.0.0"
Scrapy = "^2.4.1"
geopy = "^2.1.0"
tqdm = "^4.59.0"
pyarrow = "^3.0.0"

[tool.poetry.dev-dependencies]
mypy = "^0.812"
black = "^20.8b1"
jupyterlab = "^3.0.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
