[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
POSTGRES_DB = "imoveis"
max_amenities = 10

[default.metro_trem]
[default.metro_trem.rj]
    urls = [
        "https://pt.wikipedia.org/wiki/Metr%C3%B4_do_Rio_de_Janeiro",
        "https://pt.wikipedia.org/wiki/SuperVia",
    ]

[default.sites]
    [default.sites.vivareal]
        site = "https://www.vivareal.com.br"
        api = "glue-api.vivareal.com"
        portal = "VIVAREAL"

    [default.sites.zapimoveis]
        site = "https://www.zapimoveis.com.br"
        api = "glue-api.zapimoveis.com.br"
        portal = "ZAP"


[development]
DEBUG = true
max_page = 2
SQLALCHEMY_DATABASE_URI  = 'postgresql://postgres:postgres@localhost:15432/listing'
SECRET_KEY = "5e2b552d-b1d8-489e-9547-2f3475b9ee12"

[production]
DEBUG = false
max_page = -1
SQLALCHEMY_DATABASE_URI  = 'postgresql://postgres:postgres@db:15432/listing'
SECRET_KEY = "83457483jsg83275-87345"
