[default]
SQLALCHEMY_TRACK_MODIFICATIONS = false
POSTGRES_DB = "imoveis"

[default.metro_trem]
[default.metro_trem.rj]
    urls = [
        "https://pt.wikipedia.org/wiki/Metr%C3%B4_do_Rio_de_Janeiro",
        "https://pt.wikipedia.org/wiki/SuperVia",
    ]

[default.metro_trem.sp]
    urls = [
        "https://pt.wikipedia.org/wiki/Metr%C3%B4_de_S%C3%A3o_Paulo",
    ]

[default.sites]
    [default.sites.vivareal]
        site = "https://www.vivareal.com.br"
        api = "glue-api.vivareal.com"
        portal = "VIVAREAL"

    [default.sites.zapimoveis]
        site = "https://www.zapimoveis.com.br"
        api = "glue-api.zapimoveis.com.br"
        portal = "ZAP"


[development]
DEBUG = false
max_page = -1
SQLALCHEMY_DATABASE_URI  = 'postgresql://postgres:postgres@localhost:15432/listing'
force_update = true

[production]
DEBUG = false
max_page = -1
SQLALCHEMY_DATABASE_URI  = 'postgresql://postgres:postgres@db:5432/listing'
force_update = false
