title = "ConfigFile"

site = ["zap", "vivareal"]
local = "Tijuca"
# pegar_bairro = false
max_page = 10

valor_minimo = 50
valor_maximo = 3500

urls_metro_trem = [
    "https://pt.wikipedia.org/wiki/Metr%C3%B4_do_Rio_de_Janeiro",
    "https://pt.wikipedia.org/wiki/SuperVia",
]

[webdriver]
    command_executor = "http://localhost:4444/wd/hub"
    [webdriver.desired_capabilities]
        browserName = "firefox"
        browserVersion = "83.0"
        [webdriver.desired_capabilities."selenoid:options"]
            enableVNC = true
            enableVideo = false
            enableLog = false

[zap]
    url = "https://www.zapimoveis.com.br"
    tipo_contrato = "Alugar"
    tipo_propriedade = "Apartamento"

[vivareal]
    url = "https://www.vivareal.com.br/"
    tipo_contrato = "Alugar"
    tipo_propriedade = "Apartamento"

[imovelweb]
    url = "https://www.imovelweb.com.br/"
    tipo_contrato = "Alugar"
    tipo_propriedade = "Apartamento (Todos)"
