title = "TOML configfile"

[zap]
    url = "https://www.zapimoveis.com.br"
    tipo_contrato = ["Alugar", "Comprar", "Lançamentos"]
    tipo_propriedade = ["Mostrar todos", "Apartamento", "Casa"]

[vivareal]
    url = "https://www.vivareal.com.br/"
    tipo_contrato = ["Alugar", "Comprar", "Imóveis Novos"]
    tipo_propriedade = ["Mostrar todos", "Apartamento", "Casa"]
