title = "TOML configfile"

uf = ["RJ", "SP"]

[zap]
    url = "https://www.zapimoveis.com.br/{tipo_contrato}/{tipo_propriedade}/{uf}+{cidade}+{zona}+{bairro}"

    [zap.tipo_contrato]
        aluguel = ["aluguel"]

    [zap.tipo_propriedade]
        apartamento = ["apartamentos"]


[vivareal]
    url = "https://www.vivareal.com.br/{tipo_contrato}/{uf}/{cidade}/{zona}/{bairro}/{tipo_propriedade}"

    [vivareal.tipo_contrato]
        "aluguel" = ["aluguel"]

    [vivareal.tipo_propriedade]
        "apartamento" = ["apartamento_residencial"]
